### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-cashier-plugin#15]
On OctoberCms plugin's site the documentation tab show :
````
Event::listen('offline.cashier::subscription.check', function ($user, $component) {
    if ( ! $user) {
        return false;
    }

    if ($user->profile->payment_method === 'creditcard') {
        return $user->subscribed($component->property('subscription'));
    }

    return $user->profile->expires_at->gt(Carbon::now());
});
````
Is there an error with `$user->profile` propertie!?  
Always returning a `null` value.

````
$user = \Auth::getUser();  // OFFLINE\Cashier\Models\User 
$user->profile;                 // null
```` 
I'm trying to get user current subscription status to clearly display subscription informartions : 
 - Subscription
 - Plan
 - Begin date
 - Next due date
 - ...
 - and first of all : an "subscribtion cancel/resume" button.

**Comment by tobias-kuendig** [comment]
That example is wrong. It comes from an app of mine where I have added a Profile model to each User.

```php
        UserModel::extend(function (Model $model) {
            $model->hasOne['profile'] = Profile::class;
        });
```
Have you tried getting the subscription information like this:

* https://laravel.com/docs/7.x/billing#checking-subscription-status

**Comment by damsfx** [comment]
Okay, I didn't understand where that `profile` was coming from.  
Thank's for clarification.


For subscription status, it's ok ... the only issue I have left is to display invoices list with start/end dates [#11](https://github.com/OFFLINE-GmbH/oc-cashier-plugin/issues/11)
