### ISSUE TITLE
Please version the latest code

### ISSUE THREAD

**Issue by angelcoding** [OFFLINE-GmbH/oc-cashier-plugin#16]
The version of this plugin is tagged at v1.0.7, but there has since been some changes in the master branch. Especially the composer,json changes that will allow automatic October plugin installation. 

Can you please version this latest code to a new tag so composer automatically installs the plugin?

**Comment by tobias-kuendig** [comment]
Done! https://packagist.org/packages/offline/oc-cashier-plugin

**Comment by angelcoding** [comment]
Thank you!
