### ISSUE TITLE
Error: Call to a member function create() on null

### ISSUE THREAD

**Issue by blakej115** [OFFLINE-GmbH/oc-cashier-plugin#17]
I'm getting `Error: Call to a member function create() on null` in classes/Billable.php on line 388 whenever debugging and trying to use the Event listener provided in the docs and submit a test payment (Using test Stripe tokens) via the StripeElementsForm component. Any idea why this happens?

```
    public function boot()
    {
        parent::boot();
    
        Event::listen('offline.cashier::stripeElementForm.submit', function ($post) {
            $token = $post['token']['id'] ?? null;
            if ( ! $token) {
                throw new \RuntimeException('Stripe token is missing!');
            }
    
            $user = \Auth::getUser();
            $user->newSubscription('main', 'users-selected-plan-id')->create($token);
    
            return [
                'redirect' => \Url::to('thank-you')
            ];
        });
    }
```

Here's the error thrown from the PHP error logs:
`PHP message: Stripe Notice: Undefined property of Stripe\Customer instance: sources`

It appears that ->sources does not exists. Here is the line in question in classes/Billable.php on line 388:
`$card = $customer->sources->create(['source' => $token]);`

**Comment by tobias-kuendig** [comment]
What version of laravel/cashier do you have installed?

    composer info laravel/cashier | grep versions

**Comment by blakej115** [comment]
@tobias-kuendig 
`versions : * v7.2.2`

**Comment by tobias-kuendig** [comment]
Can you try and downgrade this to `7.0`? According to the composer.lock file, 7.0.11 should be installed.

https://github.com/OFFLINE-GmbH/oc-cashier-plugin/blob/master/composer.lock#L468

**Comment by angelcoding** [comment]
I'm having the same issue.
FYI, forcing laravel/cashier to 7.0.11 didn't work for me.

The latest Stripe API version has breaking changes - [https://stripe.com/docs/upgrades#2020-08-27](https://stripe.com/docs/upgrades#2020-08-27)

> The sources property on Customers is no longer included by default. You can expand the list but for performance reasons we recommended against doing so unless needed.

Is it possible to get this fixed? 
In the meantime I'm desperately trying to figure out how to change the default API versoin from within Stripe ...

**Comment by angelcoding** [comment]
Not sure it's the best solution just yet, but adding `Stripe\Stripe::setApiVersion('2020-03-02');` to the `boot()` method of my plugin has helped.

**Comment by tobias-kuendig** [comment]
This problem is resolved in v2 of the plugin as it uses Laravel Cashier v9
