### ISSUE TITLE
An exception has been thrown during the rendering of a template ("The specified file extension [js] is invalid.").

### ISSUE THREAD

**Issue by mcziel** [OFFLINE-GmbH/oc-cashier-plugin#20]
Hi, Im trying to set up this plugin, I already configure my api keys, but when I try to use the strip elements form I got these:

<img width="1144" alt="Screen Shot 2021-04-27 at 8 47 43 PM" src="https://user-images.githubusercontent.com/6682458/116329678-dc224380-a799-11eb-8051-3a977f23fb00.png">

When using other components I am not getting any error.

Thank you beforehand.

**Comment by tobias-kuendig** [comment]
This is due to a change in Octoberr. You can safely rename the `tokenHandler.js` to `tokenHandler.htm` and change the import path. I will issue a fix for the plugin that changes this.

**Comment by tobias-kuendig** [comment]
There you go: [v1.0.9](https://github.com/OFFLINE-GmbH/oc-cashier-plugin/commit/f5f6ce569445199853de84ccaa8ff9543dc71597)

Thank you for this report!

**Comment by mcziel** [comment]
Awesome, thank you!
