### ISSUE TITLE
Composer.lock Errors when installing

### ISSUE THREAD

**Issue by arachnadigital** [OFFLINE-GmbH/oc-cashier-plugin#21]
Hi,

I get these errors when installing Cashier via project:sync

`  Problem 1
    - offline/oc-cashier-plugin[v1.0.7, ..., v1.0.9] require laravel/cashier ^7.0 -> satisfiable by laravel/cashier[v7.0.0, ..., v7.2.2].
    - laravel/cashier 7.0.x-dev requires nesbot/carbon ~1.0 -> found nesbot/carbon[1.0.0, ..., 1.39.1] but the package is fixed to 2.48.0 (lock file version) 
by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - laravel/cashier[v7.0.0, ..., v7.2.2] require illuminate/database ~5.3 -> found illuminate/database[v5.3.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires offline/oc-cashier-plugin ^1.0 -> satisfiable by offline/oc-cashier-plugin[v1.0.7, v1.0.8, v1.0.9].`

On the latest OctoberCMS version

**Comment by tobias-kuendig** [comment]
Thank you for this bug report. This problem should no longer appear in v2 of the plugin. Please test using the latest version.
