### ISSUE TITLE
newSubscription stripe_id conflict. 

### ISSUE THREAD

**Issue by Adrion** [OFFLINE-GmbH/oc-cashier-plugin#6]
Hi there ! Nice plugin as usual, thank you ! 😄 

However I found a conflict with the offline_cashier_stripe_id property name change.
When you create a `newSubscription` it leads to a new stripe_id and then the user loses his old offline_cashier_stripe_id. 

To prevent this we must add a mutator for laravel/cashier compatibility. 

```
    /**
     * Get the stripe_id attribute.
     *
     * @return string
     */
    public function getStripeIdAttribute()
    {
        return $this->offline_cashier_stripe_id;
    }
```

Or we can simply go back to stripe_id property name. But it would be an unnecessary breaking change.  

I'll send you a simple PR for this :)

**Comment by tobias-kuendig** [comment]
Good catch, thank you for the bug report and PR. As per October's quality guidelines we need to keep the `offline_cashier_` column prefix.

Your PR referenced the wrong column so I added this bit myself in 87fedbd.

v1.0.5 is available via the Marketplace :+1:

**Comment by Adrion** [comment]
Oops indeed I was sure I edited the column prefix ^^'
