### ISSUE TITLE
Auth::getUser returns Rainlab Model on List Invoices component

### ISSUE THREAD

**Issue by yebor974** [OFFLINE-GmbH/oc-cashier-plugin#9]
Hi,

I try to use this plugin on October CMS. 

When i use the Invoices List component for the current auth user, i've no invoices. However, i've an invoice for the user on Stripe Dashboard.

After debug, the auth::getUser() returns a Ranlab User Model and not Offline Cashier User Model. In this case, i can't force use the Offline Model without redefine the list component.

This issue occurs on my Ubuntu server 18.04 LTS and not on local environment (Windows Xampp).

Thanks for your helps,

**Comment by tobias-kuendig** [comment]
The plugin should replace RainLab's AuthManager here:
https://github.com/OFFLINE-GmbH/oc-cashier-plugin/blob/master/Plugin.php#L29

Maybe you can try to debug this issue from there?

Are you using any other plugins that might interfere with the auth manager?

**Comment by yebor974** [comment]
Yes the plugin replaces the authManager and i try to override it too with new registering in my own plugin but i have the same issue.

I have only the Rainlab User plugin and Offline Cashier who have a register function to the user.auth.

So i have only this issue on ubuntu prod server not in local computer. Hard to debug on prod server :)

**Comment by tobias-kuendig** [comment]
I wonder what determines the run order of the Plugin files :thinking:

**Comment by yebor974** [comment]
Yep, i know only the $require attribute to define order to install plugin. 

I see also an $elevated attribute on Rainlab User.

**Comment by yebor974** [comment]
I found a patch by defining a new provider and register it before the 'System\ServiceProvider' in config app.php. In this provider i redefined the user.auth singleton to OffLine AuthManager

This is not so proper but it works and permits me to deliver project :)

**Comment by tobias-kuendig** [comment]
This problem is resolved in v2
